version: "3.3"
services:
  back:
    build: .
    restart: always
    links:
      - pg:pg
    depends_on:
      - pg
    ports:
      - 8000:8000
    environment:
      - DB_DSN=postgres://user:pass@pg/main
      - API_KEY=${API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${DOMAIN}
      - BASE_URL=https://${DOMAIN}
      - RECAPTCHA_PUBLIC_KEY=${RECAPTCHA_PUBLIC_KEY}
      - RECAPTCHA_PRIVATE_KEY=${RECAPTCHA_PRIVATE_KEY}

  dramatiq:
    build: .
    restart: always
    links:
      - pg:pg
      - redis:redis
    depends_on:
      - pg
    ports:
      - 8000:8000
    environment:
      - DB_DSN=postgres://user:pass@pg/main
      - REDIS_DSN=redis://redis:6379
      - API_KEY=${API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - BASE_URL=https://${DOMAIN}

  pg:
    image: postgres:12
    restart: always
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=main
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_AOF_ENABLED=yes
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data/redis:/bitnami/redis/data
